# guess1.py
# Author: Paul McGrath
# this program  asks user to input a number until they get the number generated by the program

numbertoGuess = 30 # have to start with an input


guess = int(input ("Please guess the number: "))
while guess != (numbertoGuess):
    print ("Wrong Guess")
    print ("Please re-enter the number:") # this code line is not needed- delete
    guess = int(input ("Please guess again: "))

    print ("Well done!  Yes the Number is {}!"  .format(numbertoGuess))

