# guess2.py
# Author: Paul McGrath
# this program  asks user to input a number until they get the number generated by the program
# it gives a hint -number is higher or lower
numbertoGuess = 30 # have to start with an input


guess = int(input ("Please guess the number: "))
while guess != numbertoGuess:
    if guess < numbertoGuess:
         print (" number is higher")
    else:
        print (" number is lower")
    guess = int(input ("Please guess again: "))

print ("Well done!  Yes the Number is {}!"  .format(numbertoGuess))

